//
// Created by pc on 11/29/2024.
//

#ifndef COMPILER_PROJECT_TOKENTYPE_H
#define COMPILER_PROJECT_TOKENTYPE_H
enum TokenType {
    KEYWORD,
    PUNCTUATION,
    REGULAR_DEFINITION,
    REGULAR_EXPRESSION,
    UNDEFINED
};

#endif //COMPILER_PROJECT_TOKENTYPE_H
